services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"    # puerto para apps (producer/worker)
      - "15672:15672"  # UI / dashboard
    networks:
      - rabbit_net

  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - rabbitmq
    networks:
      - rabbit_net

  worker:
    build: ./worker
    depends_on:
      - rabbitmq
    networks:
      - rabbit_net
    scale: 2   

networks:
  rabbit_net:
    driver: bridge
